services:
  db:
    image: mariadb:11
    container_name: paprika-db
    restart: unless-stopped
    environment:
      MARIADB_DATABASE: wordpress
      MARIADB_USER: wordpress
      MARIADB_PASSWORD: wordpress
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./marinadb:/var/lib/mysql

  wordpress:
    image: wordpress:php8.2-apache
    container_name: paprika-wp
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_DEBUG', true);
        define('WP_ENVIRONMENT_TYPE', 'local');
        define('PAPRIKA_TG_BOT_TOKEN', 'PAPRIKA_TG_BOT_TOKEN');
        define('PAPRIKA_TG_CHAT_ID', 'PAPRIKA_TG_CHAT_ID');

    volumes:
      - ./wp-content:/var/www/html/wp-content
    depends_on:
      - db

